### ISSUE TITLE
源码使用nodejs ci 运行时出现错误

### ISSUE THREAD

**Issue by github613555424** [eolinker/eoapi#11]
**Describe the bug**
源码使用nodejs ci 运行时出现错误
![image](https://user-images.githubusercontent.com/38872135/162677915-b83504c3-af7b-4764-93a5-601b6d8ed101.png)
源码包：eoapi-0.0.1-beta.zip
nodejs版本 16.14.2

**Comment by github613555424** [comment]
已解决，是我的环境问题，打扰了
`npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver`

**Comment by scarqin** [comment]
@github613555424 不打扰，有问题随时沟通～
