### ISSUE TITLE
 Unable to preview non-text data

### ISSUE THREAD

**Issue by douyacai1010** [eolinker/eoapi#114]
![image](https://user-images.githubusercontent.com/84163019/181686627-015831d9-975d-4047-8924-9c0620c5cbde.png)

![image](https://user-images.githubusercontent.com/84163019/181686669-5f5bc013-79bd-4dc4-959f-4c5dd2df8138.png)

application/json 无法解析吗

**Comment by scarqin** [comment]
@douyacai1010 是因为 json 太大了，会影响渲染，所以提供文件下载，这里提示语句有问题，我们优化一下。
