### ISSUE TITLE
mock数据添加不成功

### ISSUE THREAD

**Issue by douyacai1010** [eolinker/eoapi#115]
![image](https://user-images.githubusercontent.com/84163019/181717428-bb222c50-6a48-420e-9769-eefd7ea305e5.png)
![image](https://user-images.githubusercontent.com/84163019/181717535-0fb4b3a6-3074-4245-8c18-361b49b51519.png)
mock数据一直添加不成功

**Comment by scarqin** [comment]
@douyacai1010
1. 是远程数据源吗？
2. 请问你地址栏的 uuid 是多少？
3. 仅这个 API 的 mock 无法成功还是所有的 mock？

**Comment by douyacai1010** [comment]
是远程数据
所有的api都添加不了
uuid在哪里看

**Comment by scarqin** [comment]
@douyacai1010 ok，所有 API 都添加不了就不用关注 uuid。
感谢反馈，我们复现后尽快修复

**Comment by douyacai1010** [comment]
@scarqin 嗯嗯，我这边直接下载
![image](https://user-images.githubusercontent.com/84163019/181723985-572b18dd-7da5-4c15-89ab-614e2902d841.png)
这个使用的

**Comment by buqiyuan** [comment]
@douyacai1010 Hello~你反馈的问题已修复。如果要使用远程数据源的话，可以再更新一下[eoapi-remote-server](https://github.com/eolinker/eoapi-remote-server)的代码，或者可以使用我们的远程数据源服务器: http://8.219.85.124:3000

**Comment by douyacai1010** [comment]
> @douyacai1010 Hello~你反馈的问题已修复。如果要使用远程数据源的话，可以再更新一下[eoapi-remote-server](https://github.com/eolinker/eoapi-remote-server)的代码

好的，感谢
