### ISSUE TITLE
Layout resizing

### ISSUE THREAD

**Issue by fanzouguo** [eolinker/eoapi#116]
1、左侧边栏是否可以增加左右调整尺寸的功能，如果接口保存后的命名过长，被省略号替换掉了，那后续部分看不见，恰好前面部分文字又一样的话，很容易困惑。
![230b6fd04193b4fdfa6b0aa5d50dd21](https://user-images.githubusercontent.com/10015003/182710701-86f07eb2-0cc9-420d-b0d5-459d55da2123.png)

2、对于返回结果的数据区域，可视区过于小气了，固定高度，而且只显示了一丁点，还要上下滚动，是否可以参照 postMan 那样布局，返回数据区域整体放置到右侧，采取 100 vh 高度，查看返回数据更加便捷一些

![image](https://user-images.githubusercontent.com/10015003/182711583-ef3ecfd1-3be4-479d-ae2d-3a6d00f00ccf.png)
![image](https://user-images.githubusercontent.com/10015003/182711768-233d598b-6b32-432c-84b2-60e1ee67c563.png)

**Comment by scarqin** [comment]
@fanzouguo 感谢建议
1. 未来会做，有 pr 了通知你
2. 可以试试我们昨晚发布的最新 [1.4.0-beta](https://github.com/eolinker/eoapi/releases/tag/v1.4.0-beta) 版本，支持拖动改变列宽.
<img width="880" alt="image" src="https://user-images.githubusercontent.com/15225835/182733881-98c73533-7c59-4a7d-9e98-7604a3f4722e.png">

如果返回结果显示区域支持放在右侧，布局会更灵活，我们需要考虑下

**Comment by fanzouguo** [comment]
好的，谢谢

**Comment by buqiyuan** [comment]
@scarqin PTAL #125

**Comment by scarqin** [comment]
@fanzouguo 将在 1.5.1 版本发布，感谢你的建议～
