### ISSUE TITLE
Change uri cancel select queryParams

### ISSUE THREAD

**Issue by mojimaomao** [eolinker/eoapi#117]
![image](https://user-images.githubusercontent.com/110816180/183378380-de2b8435-d167-45b7-950e-7ba699d86939.png)

**Comment by scarqin** [comment]
![](https://user-images.githubusercontent.com/15225835/183384429-7e04d9e8-5a2d-46d1-bc21-c0ca6db48e78.png)
需要勾选

**Comment by scarqin** [comment]
Reproduce
![](https://user-images.githubusercontent.com/15225835/183386683-a52ca312-35de-4f23-8477-e1f700b3715e.png)
<img width="329" alt="image" src="https://user-images.githubusercontent.com/15225835/183386811-f687e67d-b3e7-4a64-9dd0-01b25abf9aba.png">
