### ISSUE TITLE
请求体字段更多设置展开收缩按钮显示bug

### ISSUE THREAD

**Issue by veikai** [eolinker/eoapi#122]
API文档标签页
请求体中如果字段设置了‘更多设置’，展开收缩按钮显示文字与实际展开收缩情况不符，更多设置收缩时按钮显示的是收缩，更多设置展开是按钮显示的是展开

 - OS: [Windows_NT x64 10.0.22000]
 - Version [1.4.0-beta]

**Comment by scarqin** [comment]
@veikai 下个版本修复，感谢反馈～
