### ISSUE TITLE
Multiple APIs share the same test page, resulting in mutual coverage

### ISSUE THREAD

**Issue by mojimaomao** [eolinker/eoapi#124]
例如，先打开一个已经创建的API测试页面，然后再新建一个API，新建的API页面直接就是之前已创建的API的测试页面，且没有保存为新的API按钮
![image](https://user-images.githubusercontent.com/110816180/184048318-52cf0241-ecf7-4a6f-afea-44a07c3f1bc8.png)
![image](https://user-images.githubusercontent.com/110816180/184048360-10cb29ed-00c4-4487-a8ec-4845ef5369d1.png)

或者先新建一个API，默认信息为空，然后再切换到其他已创建的API的测试页面，已创建API的测试页面也显示为空，需要切换到其他页面再切换回测试页面，才能正常显示信息
![image](https://user-images.githubusercontent.com/110816180/184047820-3c276442-0d1c-4a9a-9e38-12e226b60f1b.png)
![image](https://user-images.githubusercontent.com/110816180/184047887-d65e4f58-9bd7-46ba-a36f-49531740bd4b.png)
![image](https://user-images.githubusercontent.com/110816180/184048130-43bd5bea-524e-4c5f-bdc8-8768ff6b114b.png)

**Comment by scarqin** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/15225835/184049802-823ddd19-fb05-45c3-8c73-d5273ed1d2f0.png">
方便截图一下如图所有 API 的uuid 吗？

**Comment by mojimaomao** [comment]
> 

我是用的客户端，要怎么查询这个uuid呢？

**Comment by scarqin** [comment]
windows F12
mac command+shift+i
打开开发者工具，然后按照我截图样式选中相应的内容

**Comment by mojimaomao** [comment]
> windows F12 mac command+shift+i 打开开发者工具，然后按照我截图样式选中相应的内容

客户端F12没有用吧，不是浏览器，按了F12没反应

**Comment by scarqin** [comment]
@mojimaomao 可以打开的，试过好几种姿势复现不了，你试试关闭所有 Tab，然后清空这个再尝试下复现
![](https://user-images.githubusercontent.com/15225835/184081067-00f0fe9b-1112-4fb0-a333-e2c2dcf2feda.png)

**Comment by luohe** [comment]
> > windows F12 mac command+shift+i 打开开发者工具，然后按照我截图样式选中相应的内容
> 
> 客户端F12没有用吧，不是浏览器，按了F12没反应

mac尝试一下command+option+i
