### ISSUE TITLE
分组上应增加一个刷新功能

### ISSUE THREAD

**Issue by wyh137815840** [eolinker/eoapi#127]
当多个人同时维护一个分组时，分组没有刷新功能。目前只能关掉再开来刷新数据，不是很方便
<img width="445" alt="截屏2022-08-14 18 14 19" src="https://user-images.githubusercontent.com/48979107/184532493-90783c58-730b-4a1a-a8f6-032f47a40e61.png">

**Comment by scarqin** [comment]
@wyh137815840 刷新快捷键：
windows：ctrl+R 或者 F5
mac：command+R
