### ISSUE TITLE
请优化api测试结果的文件流保存功能

### ISSUE THREAD

**Issue by mojimaomao** [eolinker/eoapi#128]
当api测试返回的结果是文件流时：
1、默认保存的文件名是“download”，建议优化为默认原文件名
2、对于小于500K的文件，当前只能预览，不能保存为本地文件，建议增加保存为本地文件的功能

**Comment by scarqin** [comment]
@mojimaomao 
1. 默认是原文件名的，如果不是可能是 bug，方便截图下你的地址和返回头部吗？
2. 👍

**Comment by mojimaomao** [comment]
> 1. 默认是原文件名的，如果不是可能是 bug，方便截图下你的地址和返回头部吗？
![image](https://user-images.githubusercontent.com/110816180/184784378-b0c0dbfb-1d4d-4033-92d7-b1ccf01e77c1.png)
![image](https://user-images.githubusercontent.com/110816180/184784418-9ca62d3f-079f-4829-9142-a37777df91a8.png)

**Comment by scarqin** [comment]
@buqiyuan

**Comment by scarqin** [comment]
[fix(apiTest): test result return file but show text](https://github.com/eolinker/eoapi/commits/main#:~:text=fix(apiTest)%3A%20test%20result%20return%20file%20but%20show%20text)

**Comment by buqiyuan** [comment]
第2点已支持，待发版后可用。[related commit](cc0fac7e6f0bb04caeaac929820d6b8e21d61d3f)
