### ISSUE TITLE
mac客户端 导入/导出 OpenAPI(.json) 无响应

### ISSUE THREAD

**Issue by kms9** [eolinker/eoapi#130]
Before opening an issue, we recommend:
* Use English to communicate.
* Search for duplicates of [Issues](https://github.com/eolinker/eoapi/issues) and [Discussions](https://github.com/eolinker/eoapi/discussions) unresolved.

**Describe the bug**
mac客户端 导入/导出 OpenAPI(.json) 无响应

**Desktop (please complete the following information):**
 - OS: mac
 - Version: 版本1.6.0 (1.6.0)

**Comment by scarqin** [comment]
@kms9 请提供一下两个插件版本，感谢

**Comment by buqiyuan** [comment]
@kms9 你好！刚刚修复了导出OpenAPI，插件版本号是1.0.20，重装该插件再试下导出看看
