### ISSUE TITLE
Cooperation request

### ISSUE THREAD

**Issue by tzwhyqq** [eolinker/eoapi#136]
Before opening an issue, we recommend:
* Use English to communicate.
* Search for duplicates of [Issues](https://github.com/eolinker/eoapi/issues) and [Discussions](https://github.com/eolinker/eoapi/discussions) unresolved.

**Is your feature request related to a problem? Please describe.**
1、添加团队管理功能。
2、团队权限功能。
3、项目可以分组。每个组可以进行权限分配。
4、测试用例增强，有些功能需要多个测试用例组合测试，建议加一个单独的模块管理这种。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by scarqin** [comment]
Thanks for u suggestions

**Comment by scarqin** [comment]
@tzwhyqq v1.8.0-beta has release!
