### ISSUE TITLE
编辑API保存后关闭TAB页还是提示未保存

### ISSUE THREAD

**Issue by donkeywon** [eolinker/eoapi#153]
### Describe the bug

![image](https://user-images.githubusercontent.com/18396127/195258860-753c1791-ce95-443a-94ab-105de4bdca8c.png)

### Environment

- Eoapi version: 1.8.0
- Eoapi server version: 1.8.0

**Comment by scarqin** [comment]
@donkeywon 已复现，会在下个版本修复，感谢反馈～

**Comment by scarqin** [comment]
@donkeywon 新版已经发布，已修复这个问题
