### ISSUE TITLE
客户端导出openapi点击没有反应

### ISSUE THREAD

**Issue by donkeywon** [eolinker/eoapi#154]
### Describe the bug

![image](https://user-images.githubusercontent.com/18396127/195271118-be190af4-ea8f-46fb-b882-059e118f3289.png)

### Environment

- Eoapi version: 1.8.0
- Eoapi server version: 1.8.0

**Comment by donkeywon** [comment]
> @donkeywon 麻烦截图一下控制台显示看看报错； mac:command+R windows:ctrl+shift+i
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/15225835/195271535-d6542c1e-7cb3-4358-9648-9ab9fb183862.png">

这是刚打开软件时的报错
![image](https://user-images.githubusercontent.com/18396127/195272287-3912e4ca-007f-4969-a568-4514e15e5ca2.png)

这是点击导出确认的报错
![image](https://user-images.githubusercontent.com/18396127/195272363-288d4014-2ba4-4403-9a7b-cfc7d579d5dd.png)

**Comment by scarqin** [comment]
@buqiyuan 看看这个问题～

**Comment by buqiyuan** [comment]
@donkeywon 你好~是远程数据源这边导出的数据格式与插件接收的数据格式不一致的问题，麻烦升级一下 [eoapi-remote-server](https://github.com/eolinker/eoapi-remote-server) 服务端代码再尝试一下。

[related commit](https://github.com/eolinker/eoapi-remote-server/pull/14)

**Comment by donkeywon** [comment]
@buqiyuan  使用server可以导出了，但是使用本地的话还是会报错

**Comment by scarqin** [comment]
@donkeywon 我这边本地是可以成功了，方便截图一下你的报错吗？
<img width="917" alt="image" src="https://user-images.githubusercontent.com/15225835/195370194-3859a2a8-1d89-49da-938d-86e24dd5d4bb.png">

**Comment by donkeywon** [comment]
@scarqin 重启了下客户端又可以了。。。，可能之前的报错有影响吧

**Comment by donkeywon** [comment]
@scarqin 
1. 全新安装eoapi客户端然后直接导出默认的两个接口会报错，关闭重启后可以导出
![image](https://user-images.githubusercontent.com/18396127/195512679-c683e57e-0373-4fc2-94c8-39ececd792fc.png)

2. 导入第一步导出的json文件后，接口里面的内容全都没了，默认的那两个接口和自建的接口都存在这种情况
![image](https://user-images.githubusercontent.com/18396127/195513057-df6dc4f0-0a34-4606-a7b4-f6526a355c35.png)

**Comment by scarqin** [comment]
@scarqin 好～你先刷新用着，我们在排查ing
