### ISSUE TITLE
导入json时输入框双引号自动补全有问题

### ISSUE THREAD

**Issue by donkeywon** [eolinker/eoapi#155]
### Describe the bug

1. 在输入第一个双引号时自动补全了右引号，后面输入的双引号都没有自动补全。
2. 当光标右边存在右引号时，手动输入右引号会多一个右引号而不是光标右移一位
![动画](https://user-images.githubusercontent.com/18396127/195273228-55f7cbba-4e93-4bae-b4fa-9a4773880942.gif)

### Environment

- Eoapi version: 1.8.0
- Eoapi server version: 1.8.0

**Comment by scarqin** [comment]
@donkeywon 细节了👍
