### ISSUE TITLE
云空间修改分组名后，分组名消失了

### ISSUE THREAD

**Issue by foolishflyfox** [eolinker/eoapi#157]
### Describe the bug

1. 在云服务器上已经安装了 eoapi-remote-server，已经通过 eoapi 连接到该云服务器
2. 创建了一个云空间，并在其中创建了分组
3. 修改分组名
<img width="506" alt="image" src="https://user-images.githubusercontent.com/17536022/195370119-f8dfc8d1-890e-49a7-9bb5-33b9bf58bd05.png">
<img width="906" alt="image" src="https://user-images.githubusercontent.com/17536022/195367788-3a6494bb-45ee-4126-8ba0-eb2338be0aed.png">
5. 分组被删除了
<img width="391" alt="image" src="https://user-images.githubusercontent.com/17536022/195367990-1225518c-4ffb-4b1e-a937-debf85115fe2.png">

感觉是个bug，麻烦作者看一下，谢谢！

### Environment

- Eoapi Version: 1.8.0-beta
- OS: macOS Catalina 10.15.7

**Comment by scarqin** [comment]
@foolishflyfox 复现了，感谢反馈，下个版本修复，最快周四发版

**Comment by foolishflyfox** [comment]
作者回复好快，点赞！！！

**Comment by scarqin** [comment]
@foolishflyfox 新版已经发布，已修复这个问题
