### ISSUE TITLE
意见收集：支持部署 Web，不需要下载客户端？

### ISSUE THREAD

**Issue by scarqin** [eolinker/eoapi#158]
最近有收到一些用户反馈觉得需要下载桌面端有一些麻烦，站在产品设计者的角度：
1. Web 不需要安装，部署更方便
2. 桌面端加载本地资源，速度更快

所以想听听大家关于这个提议的想法，协助我们一起设计～

ps：Web 短期内还可能不支持插件

**Comment by donkeywon** [comment]
个人感觉还是很有必要支持部署web服务的，这种方式可能需要把eoapi-remote-server整合到web服务里，类似于yapi、torna、metersphere那种私有化部署方式，对于以下两种场景比较方便
1. 直接整合到本地docker开发环境，类似于我做的一个 [通用本地docker开发环境](https://github.com/donkeywon/docker_centos)，里面已经整合了yapi、torna、metersphere和eoapi-server，启动开发环境后可以直接无缝衔接
2. 企业内部私有化部署
