### ISSUE TITLE
插件无法debug

### ISSUE THREAD

**Issue by FoSuCloud** [eolinker/eoapi#175]
### Describe the bug

找不到对应目录。HOME应该指向什么位置呢？
![image](https://user-images.githubusercontent.com/49218295/198884882-fe6ad20e-9df2-4ed9-8139-0f1917aa8cd3.png)
![image](https://user-images.githubusercontent.com/49218295/198884965-f1053ba4-2a74-4af2-9f2e-16aee245b938.png)

### Environment

node 14.18.0

**Comment by scarqin** [comment]
@FoSuCloud debug 需要客户端（基座)，[下载地址](https://github.com/eolinker/eoapi/releases )
<img width="877" alt="image" src="https://user-images.githubusercontent.com/15225835/198885873-1a4482b2-6cdd-4ed0-9e37-c1152d385f87.png">
插件目录下运行：
<img width="907" alt="image" src="https://user-images.githubusercontent.com/15225835/198885952-0fb82640-20b5-456d-9299-caeada3b8d1f.png">
就会看到有外链
<img width="523" alt="image" src="https://user-images.githubusercontent.com/15225835/198885977-c263127c-3a63-404f-adc2-69e805deea1c.png">
打开客户端就可以看到被 debug 的插件

**Comment by scarqin** [comment]
https://developer.eoapi.io/api/get-started.html#%E8%B0%83%E8%AF%95
开发者文档

**Comment by FoSuCloud** [comment]
我已经安装运行了eoapi，成功运行serve:web命令。但是electron没有安装成功，这就是找不到基座的原因吗

**Comment by scarqin** [comment]
@FoSuCloud 对，开发插件需要桌面端，你可以不用运行，安装桌面端也可以调试插件的。
你想要开发什么插件呢～

**Comment by FoSuCloud** [comment]
好的，了解了，目前还在了解哈
