### ISSUE TITLE
插件是如何被加载进app的？

### ISSUE THREAD

**Issue by FoSuCloud** [eolinker/eoapi#176]
### Describe the bug

已经把插件添加进.eo目录，但是并没有被app加载进去。请问app的加载插件流程是怎么样的？
`export const importFunc = (data = {}) => {
  console.log('demo  data:',data)
  return {
    name: 'eoapi',
  };
};
`

### Environment

node 14.18.0

**Comment by kungfuboy** [comment]
需要在插件的package.json 文件中做好相关的配置，这样Eoapi在启动时才能知道这是个什么类型的插件，入口文件是哪个，以及导出的方法名是什么？
在你的例子里，importFunc就是导出的方法名，所以需要在 package.json 的 features.apimanage.import.action 字段中配好这个字段。可以参照官方的例子：https://github.com/eolinker/eoapi-extensions/blob/main/packages/feature/import/openapi/package.json

**Comment by FoSuCloud** [comment]
我想了解下全流程是怎么样的。
首先 eo debug。把组件链接到.eo目录下的node_modules，然后app启动，寻找机器.eo目录下的node_modules的依赖？

**Comment by scarqin** [comment]
@FoSuCloud 对，然后 require
