### ISSUE TITLE
点击分享按钮 没有需要分享的url，是空的，麻烦大神怎么解决？

### ISSUE THREAD

**Issue by mrsun123** [eolinker/eoapi#182]
### Describe the bug

![image](https://user-images.githubusercontent.com/7961852/200513094-80eb585d-bcbb-4591-873e-d50c031a308f.png)

### Environment

- 版本: 1.9.1
- Electron: 19.0.6
- Chromium: 102.0.5005.115
- Node.js: 16.14.2
- V8: 10.2.154.8-electron.0
- OS: Windows_NT x64 10.0.19044

**Comment by scarqin** [comment]
@mrsun123 你的 eoapi-remote-server 是什么时候部署的，什么 docker 版本呢？

**Comment by scarqin** [comment]
@mrsun123 hello,解决了吗

**Comment by shiasn** [comment]
刚刚更新完，遇到了同样的问题，云端服务是正常的，但是软件当中天写完云端服务主机地址后，发送的是这样的请求
<img width="823" alt="截屏2022-11-10 05 57 26" src="https://user-images.githubusercontent.com/17953714/200952461-b32f9d42-ee7a-4e38-9d7c-e261106fa5d3.png">

**Comment by scarqin** [comment]
@shiasn 方便看下配置的 URL 吗？
<img width="902" alt="image" src="https://user-images.githubusercontent.com/15225835/200984463-59ec32cb-bb1d-4700-9afc-41d56545fa1e.png">

**Comment by shiasn** [comment]
@scarqin 我也有点迷糊了，印象里 1.8.2 版本中并没有填写 `https://`，然后出现分享链接空白是我更新了远端服务，然后打开本地软件，然后就发现分享是空白的，然后进入设置，点击链接就出现了我之前说的情况，我加上 `https://`，就正常了，但是有个问题，这个分享链接我无法在浏览器中打开

**Comment by scarqin** [comment]
@scarqin 你远程服务部署的是最新的吗？
如果是最新的话可以看下 docker logs 有没有报错，打不开应该是 web 没有启动的原因。

**Comment by mrsun123** [comment]
需要部署最新的eoapi-remote-server？

**Comment by scarqin** [comment]
@mrsun123 对，API 分享是最新功能～1.9.0 开始支持。
如何升级可见：[服务升级](https://docs.eoapi.io/docs/storage.html#%E6%9C%8D%E5%8A%A1%E5%8D%87%E7%BA%A7)
