### ISSUE TITLE
rest参数没有自动填充

### ISSUE THREAD

**Issue by donkeywon** [eolinker/eoapi#184]
### Describe the bug

记得之前某个版本在url路径输入{name}后会自动添加一个rest参数

![image](https://user-images.githubusercontent.com/18396127/201287070-749fcef8-c1c3-4012-b26e-dddb01f0ec6a.png)

### Environment

- eoapi version: 1.9.1
- eoapi server version: 1.9.1

**Comment by scarqin** [comment]
@donkeywon 复现了，下个版本修复
