### ISSUE TITLE
使用docker在线部署，Nginx 错误

### ISSUE THREAD

**Issue by GriMu** [eolinker/eoapi#187]
大佬，在线部署时，服务都启动了，数据库和后端服务都能正常访问，但是eoapi服务无法访问，3002端口正常，nginx报这个错
![image](https://user-images.githubusercontent.com/38001542/201625612-d26488b7-0fb3-4858-9cd6-5fb496d04100.png)
![image](https://user-images.githubusercontent.com/38001542/201625746-f124b118-6383-4121-a2ce-3d7f7046dda3.png)
![image](https://user-images.githubusercontent.com/38001542/201625930-c33e127d-aafa-4d39-aade-8fd11d449a9a.png)
能帮忙看看吗，谢谢

**Comment by scarqin** [comment]
@buqiyuan 协助看看

**Comment by scarqin** [comment]
@GriMu 服务无法访问的表现是什么？打开 3002 无法链接还是？

**Comment by scarqin** [comment]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/15225835/201626990-826812fb-3e73-4685-a1a8-42560dd03a90.png">
如果使用桌面端，请提供一下你的桌面端信息，同时提供一下你部署的 server 版本。

**Comment by GriMu** [comment]
> @GriMu 服务无法访问的表现是什么？打开 3002 无法链接还是？
是的，公网访问转了一会后无法链接，服务器中访问是这个
![image](https://user-images.githubusercontent.com/38001542/201636340-fd0b44ea-d92d-4262-894a-709cc8d4cf44.png)
，我是直接用这个手册部署的
![image](https://user-images.githubusercontent.com/38001542/201636030-927323b3-2a69-4956-a108-d81454537362.png)
，没有桌面端，

**Comment by scarqin** [comment]
@GriMu 
1. 浏览器打开试试
2.看一下 localhost:3000/api/system/status 接口返回

**Comment by GriMu** [comment]
> @GriMu
> 
> 1. 浏览器打开试试
>    2.看一下 localhost:3000/api/system/status 接口返回

![image](https://user-images.githubusercontent.com/38001542/201638655-9815bcc9-6011-4b95-b983-ada1ed62413c.png)

**Comment by scarqin** [comment]
@GriMu 重定向正常的，你用浏览器打开试试
<img width="850" alt="image" src="https://user-images.githubusercontent.com/15225835/201639018-b46bd3a7-39c6-4b44-bb41-a8ab4defe143.png">
![image](https://user-images.githubusercontent.com/15225835/201639062-58eeace6-cbed-4a23-a057-769d60b76af6.png)
