### ISSUE TITLE
Are there plans to support importing interfaces on existing Eolink?

### ISSUE THREAD

**Issue by ATQQ** [eolinker/eoapi#19]
Such as the title

**Comment by scarqin** [comment]
Yes, it will support importing apis in swagger, eolink and other formats in the next few months

**Comment by scarqin** [comment]
@ATQQ 
Feature has been added to our Roadmap!
![](https://user-images.githubusercontent.com/15225835/169748140-0f10d983-ab0a-4f68-a7c0-1b522c31240e.png)

**Comment by scarqin** [comment]
@kungfuboy will support it

**Comment by lizy-CZ** [comment]
这个 eoapi 跟 收费的 eolink 是什么关系？

**Comment by scarqin** [comment]
@lizy-CZ https://community.eolink.com/d/34163-fang-tan-eotalk-vol01eoapiwo-men-xi-wang-yi-kai-yuan-de-fang-shi-gou-jian-api-sheng-tai-xi-tong
可以看看这个

**Comment by scarqin** [comment]
@ATQQ 导入 Eolink 插件已经上架啦，可以在插件市场进行下载
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/15225835/189282133-0cfeddc7-16a6-4dcb-b224-a42fb0eb7810.png">
