### ISSUE TITLE
搜索的改进建议

### ISSUE THREAD

**Issue by mcxinyu** [eolinker/eoapi#192]
### Describe the bug

希望能直接搜索接口里面的字符，
例如下面的接口，可以通过搜索`weather`查询到接口
![3af22ad9daaf2d842a24141cbfdbb7e](https://user-images.githubusercontent.com/9566116/202994183-7e490e12-e4c7-4205-8cb9-30a442d37d48.png)

### Environment

- 版本: 1.10.0
- Engine: webkit
- EngineVs: 537.36
- Supporter: chrome
- SupporterVs: 107.0.0.0
- System: windows
- SystemVs: 10

**Comment by scarqin** [comment]
@mcxinyu 下个版本支持
