### ISSUE TITLE
无法连接云

### ISSUE THREAD

**Issue by markla2014** [eolinker/eoapi#194]
### Describe the bug

无法连接私有云服务器
![图片](https://user-images.githubusercontent.com/11838376/203030713-228fa06d-bb96-4037-801e-081e58be5d66.png)

### Environment

![图片](https://user-images.githubusercontent.com/11838376/203030787-5c67e4a5-b679-4653-95fd-bc577aaa852c.png)

最新

**Comment by scarqin** [comment]
@markla2014 https://docs.eoapi.io/docs/storage.html#%E6%9C%8D%E5%8A%A1%E7%9B%91%E6%8E%A7
看一下 docker 有没报错

**Comment by markla2014** [comment]
没报错，请问dokcer 起来界面是跟eopi 一样不，我用node 直接起的，只是显示了swage api 前端是啥？

**Comment by scarqin** [comment]
@markla2014 不一样，Docker 部署了三个服务（前端/后端/测试服务），Node 直接启动只是后端。

**Comment by scarqin** [comment]
@markla2014 无法连接看看控制台返回的内容。

**Comment by markla2014** [comment]
额，如果这样只能docker启动是吧

**Comment by scarqin** [comment]
@markla2014 是的，部署手册可见：https://docs.eoapi.io/docs/storage.html
