### ISSUE TITLE
没有地方写接口的介绍或者使用说明

### ISSUE THREAD

**Issue by mcxinyu** [eolinker/eoapi#195]
### Describe the bug

如题，接口需要写说明的时候，似乎没有地方写呢？

### Environment

- 版本: 1.10.0
- Engine: webkit
- EngineVs: 537.36
- Supporter: chrome
- SupporterVs: 107.0.0.0
- System: windows
- SystemVs: 10

**Comment by scarqin** [comment]
Dupulicated: #86
