### ISSUE TITLE
关于 docker-compose 编排的一些疑问

### ISSUE THREAD

**Issue by cainb** [eolinker/eoapi#198]
下方截图中高亮的  eoapi-test-server 部分只是用于实际运行环境区分，还是说是用于提供测试和 mock 功能的支撑？生产环境部署时是否可以省略？

![Screenshot_2022-11-25-08-09-27-362_com.github.android.jpg](https://user-images.githubusercontent.com/48700331/203876934-d7c8452b-cccc-4ca9-b2dd-8c9926cb12eb.jpg)

**Comment by scarqin** [comment]
@cainb 用于测试服务支撑，如果你使用桌面端，那可以不部署。
<img width="849" alt="image" src="https://user-images.githubusercontent.com/15225835/203884693-f948b728-b2b9-4f86-985d-054d9c61fdb8.png">
如果你使用 web 并且想在 web 发起测试，那需要部署。

**Comment by cainb** [comment]
> @cainb 用于测试服务支撑，如果你使用桌面端，那可以不部署。
> <img width="849" alt="image" src="https://user-images.githubusercontent.com/15225835/203884693-f948b728-b2b9-4f86-985d-054d9c61fdb8.png">
> 如果你使用 web 并且想在 web 发起测试，那需要部署。
> 

好的，谢谢解惑！

**Comment by scarqin** [comment]
我补充了一下说明在：https://docs.eoapi.io/docs/storage.html#docker-%E7%BC%96%E6%8E%92%E6%9C%8D%E5%8A%A1%E8%A7%A3%E6%9E%90

有空可以协助看看是否清晰～

**Comment by cainb** [comment]
> 我补充了一下说明在：https://docs.eoapi.io/docs/storage.html#docker-%E7%BC%96%E6%8E%92%E6%9C%8D%E5%8A%A1%E8%A7%A3%E6%9E%90
> 
> 有空可以协助看看是否清晰～

嗯嗯，刚看到了，很清晰（~
