### ISSUE TITLE
导入API数据为空时，按钮状态异常

### ISSUE THREAD

**Issue by xiguapengpeng** [eolinker/eoapi#207]
### Describe the bug

不选择文件点击“确认”，按钮的loading无法解除
![bug](https://user-images.githubusercontent.com/25153667/207541491-2f484861-7471-4760-970c-4a9de145a7db.gif)

### Environment

- EoApi Version 1.11.0

**Comment by scarqin** [comment]
@xiguapengpeng 感谢反馈，下个版本修复～
