### ISSUE TITLE
One tab cannot input parameters

### ISSUE THREAD

**Issue by littlebuzi** [eolinker/eoapi#211]
### Describe the bug

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34567725/209133184-9a2b8cf9-8763-4179-81bf-d5c054844766.png">
One tab cannot be used to enter parameters. Others can

### Environment

版本：1.11.0
Install Location：/Applications/Eoapi.app/Contents/MacOS
Electron：21.3.0
Chromium：106.0.5249.181
Node.js：16.16.0
V8：10.6.194.26-electron.0
OS：MAC Darwin x64 22.1.0

**Comment by scarqin** [comment]
@littlebuzi Reproduction, will be fixed in the next version.
