### ISSUE TITLE
Extension market web preview

### ISSUE THREAD

**Issue by scarqin** [eolinker/eoapi#44]
![](https://user-images.githubusercontent.com/15225835/169944611-b1674028-3d97-4e68-a28f-7741076d5fcb.png)
这里改成，目前 web 端暂不支持插件广场，请【下载桌面端】（绿色按钮）；
然后点击后展示下拉框如图；
![](https://user-images.githubusercontent.com/15225835/169944737-dadc48e9-ea77-4029-96a4-3dc54ebd6443.png)

**Comment by kungfuboy** [comment]
用这个方式会不会更好？

**Comment by scarqin** [comment]
@kungfuboy Are you done？in which branch。
