### ISSUE TITLE
Fix Modal and dropdown cover the browserview

### ISSUE THREAD

**Issue by eolinker** [eolinker/eoapi#6]
relate issue：https://github.com/electron/electron/issues/16854
![image](https://user-images.githubusercontent.com/15225835/159853163-c7133849-5e74-47f3-bdf0-0acde9a63e8e.png)

train of thought：
* browserview z-index
* new a browserview to mock dropdown and modal
* set main view background transparent，setTopBrowserView change view z-index

**Comment by scarqin** [comment]
relate issue：https://github.com/electron/electron/issues/15899
