### ISSUE TITLE
是否会增加文档分享功能

### ISSUE THREAD

**Issue by zqqq** [eolinker/eoapi#66]
如题，提供一个公开或者可以设置密码的链接，分享出去给需要对接的人员查看API

**Comment by scarqin** [comment]
@zqqq 感谢建议，我们考虑一下，方便提供一下你们目前的协作流程吗？

**Comment by sugarlesss** [comment]
同求，一个公开链接，加上密码访问，就可以给需要对接的人员查看 API 了。

**Comment by scarqin** [comment]
@zqqq @sugarlesss 因为目前是本地的数据源，分享的话需要将数据上传到云，如果和 Eolink 合作一个插件将 API 发布到 Eolink，最终返回一个在线文档，这种体验可以接受吗？

**Comment by wuchuguang** [comment]
要以项目为基础来做分享。
项目，分组，API（三层概念）

**Comment by wuchuguang** [comment]
项目团队管理，
分享管理。

**Comment by wuchuguang** [comment]
要搞个eoapi-server。
eoapi-client(客户端)可以设置连接哪个eoapi-server。
这样小团队，小公司群体更想用

**Comment by scarqin** [comment]
@wuchuguang 已经支持啦

**Comment by scarqin** [comment]
@wuchuguang @sugarlesss @zqqq @lilimul API 分享功能正在规划中，最快会在 v1.9.0 和大家见面

**Comment by scarqin** [comment]
@wuchuguang @sugarlesss @zqqq @lilimul 已发布～
![image](https://user-images.githubusercontent.com/15225835/199442412-dc560640-4275-43e3-86d0-3376c67fe6c8.png)
