### ISSUE TITLE
json数组里面的元素是无名的，这个应该怎么输入啊

### ISSUE THREAD

**Issue by ArthurianCN** [eolinker/eoapi#73]
这种json格式不支持的吗？或者说这种格式应该怎么输入啊？

![image](https://user-images.githubusercontent.com/63100792/173980203-9c8139da-f28e-4664-a240-5b6c5a8c4de6.png)

![image](https://user-images.githubusercontent.com/63100792/173980094-38deff3d-6e47-4a6d-9419-1628f614c818.png)

**Comment by scarqin** [comment]
@ArthurianCN 
![](https://user-images.githubusercontent.com/15225835/173980967-96d13943-dff5-4d21-a961-7165c863452c.png)

**Comment by scarqin** [comment]
@kungfuboy follow this issue
![](https://user-images.githubusercontent.com/15225835/173981039-7788eebb-f1ce-447a-a8ab-8889d5e28e48.png)
After import,array value lose
![](https://user-images.githubusercontent.com/15225835/173981073-fee6f105-7ac5-4e52-8d3a-5bac9eeab1bb.png)

**Comment by ArthurianCN** [comment]
> @ArthurianCN ![](https://user-images.githubusercontent.com/15225835/173980967-96d13943-dff5-4d21-a961-7165c863452c.png)

Thank you very much

**Comment by ArthurianCN** [comment]
@scarqin When Content-Type is application/x-msdownload, I can see the json in postman, but I can't see the json in EOAPI.

![image](https://user-images.githubusercontent.com/63100792/174053909-c2436bed-cb50-4fb2-ab89-ed5518845c6a.png)
![image](https://user-images.githubusercontent.com/63100792/174054842-c16d117a-076c-48b4-999a-417c5ae9498f.png)

**Comment by scarqin** [comment]
@ArthurianCN Thanks for reminding,it will support in #59

**Comment by kungfuboy** [comment]
> @kungfuboy follow this issue ![](https://user-images.githubusercontent.com/15225835/173981039-7788eebb-f1ce-447a-a8ab-8889d5e28e48.png) After import,array value lose ![](https://user-images.githubusercontent.com/15225835/173981073-fee6f105-7ac5-4e52-8d3a-5bac9eeab1bb.png)

Fixed
