### ISSUE TITLE
The response is text but isn't shown in eoapi 1.2.0-beta

### ISSUE THREAD

**Issue by ArthurianCN** [eolinker/eoapi#78]
![image](https://user-images.githubusercontent.com/63100792/174511617-5373f770-e664-4d6e-b479-b98d55ac642b.png)
This is the response.
![image](https://user-images.githubusercontent.com/63100792/174511680-f9b9fa8d-fa0a-49c4-bf38-ba579af15d0c.png)

**Comment by scarqin** [comment]
@ArthurianCN content-type is application/x-msdownload？
Except for the return value related to /xxx\/*text/g, everything else is regarded as a file stream。
![](https://user-images.githubusercontent.com/15225835/174512047-84ad4a04-aca9-4c31-8822-81032f100a15.png)
I have to figure out how to implement it better.

**Comment by ArthurianCN** [comment]
> @ArthurianCN content-type is application/x-msdownload？ Except for the return value related to /xxx/*text/g, everything else is regarded as a file stream。 ![](https://user-images.githubusercontent.com/15225835/174512047-84ad4a04-aca9-4c31-8822-81032f100a15.png) I have to figure out how to implement it better.

Yes. Content-type is application/x-msdownload
