### ISSUE TITLE
Is it possible to see all request history

### ISSUE THREAD

**Issue by FirewineXie** [eolinker/eoapi#79]
是否可以添加一个请求历史的功能，或许我可以能够查看历史请求例如 Postman 的历史一样。

**Comment by scarqin** [comment]
在这里～
![](https://user-images.githubusercontent.com/15225835/174559090-8484748d-1b92-4f51-8970-598cbccf5ad4.png)
@FirewineXie

**Comment by FirewineXie** [comment]
不好意思，我的意思是，是不是能有一个左边有一个请求历史的按钮，是以请求历史时间分组或者其他分组。不一定我请求的接口就是业务接口，或者就是一个临时的一个调用接口

**Comment by scarqin** [comment]
@FirewineXie 感谢，收到你的反馈，我们考虑下～

**Comment by scarqin** [comment]
@FirewineXie 预计下个版本会支持

**Comment by scarqin** [comment]
@FirewineXie https://github.com/eolinker/eoapi/releases
