### ISSUE TITLE
Environment managemetn： new env should has placeholder name："new Environment"

### ISSUE THREAD

**Issue by scarqin** [eolinker/eoapi#8]
![origin_img_v2_820c383f-23d7-4564-ac53-0dde8124bd3g](https://user-images.githubusercontent.com/15225835/159619037-ad8e8ac0-f304-48d4-975c-49f92a18606b.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by buqiyuan** [comment]
I will finish this new feature on Saturday @scarqin
