### ISSUE TITLE
保存的API信息没了

### ISSUE THREAD

**Issue by ArthurianCN** [eolinker/eoapi#85]
![image](https://user-images.githubusercontent.com/63100792/175487723-599e4525-5b20-4b3a-b553-cad81da4a562.png)
本来创建了两个分组，保存了2个API，刚刚添加第3个的时候，提示保存成功，但是分组里面看不到，把软件重启后，之前保存的API也没有了

**Comment by kungfuboy** [comment]
@buqiyuan bu

**Comment by scarqin** [comment]
@ArthurianCN 麻烦提供一下版本信息，同时切换一下到本地源看看 API 数据是不是在本地
![](https://user-images.githubusercontent.com/15225835/175505788-6d5da5a1-68ab-421f-8a1d-e13f1d407733.png)

**Comment by scarqin** [comment]
麻烦截图下：
1. 看看 indexedb 数据
![](https://user-images.githubusercontent.com/15225835/175512113-ebe42c34-c244-4993-a8b9-79be50418e91.png)
2. console 报错信息

**Comment by ArthurianCN** [comment]
> 麻烦截图下：
> 
> 1. 看看 indexedb 数据
>    ![](https://user-images.githubusercontent.com/15225835/175512113-ebe42c34-c244-4993-a8b9-79be50418e91.png)
> 2. console 报错信息

@scarqin 这个是要先安装一个developer tool吗

**Comment by scarqin** [comment]
@ArthurianCN F12 可以打开

**Comment by ArthurianCN** [comment]
@scarqin 浏览器里面F12可以。但这是Windows上安装的客户端啊

**Comment by scarqin** [comment]
@ArthurianCN 也是可以的，我们使用 Electron 技术栈

**Comment by ArthurianCN** [comment]
> @ArthurianCN 也是可以的，我们使用 Electron 技术栈

我打开软件，按F12试了，没有反应

**Comment by scarqin** [comment]
@ArthurianCN 留一下你的 QQ 我远程快速 debug 一下
