### ISSUE TITLE
Trying to use eoapi, but I am very confused about how to deploy on Alibaba Cloud

### ISSUE THREAD

**Issue by pengkang1991** [eolinker/eoapi#88]
代码已经下载到阿里云并编译好，nginx 也配置好，但是测试api提示    Request URL: https://172.17.12.4/api/unit   403  。想知道后台服务nginx如何配置？是否能提供一下linux+nginx 的部署教程，十分感谢！133144250@qq.com.
 
nginx 

   location / {
		
		root /data/eoapi/code/eoapi/src/workbench/browser/dist/;
        try_files $uri $uri/ /index.html;
        
    }

**Comment by scarqin** [comment]
@Changeeer 
1. 部署到浏览器如果没有配合 serverless，跨域测试不了，而且数据储存在本地的
2. 如果想部署到远程全公司共享，需要下载客户端，请看教程：https://www.eoapi.io/docs/storage.html
