### ISSUE TITLE
部分API没有显示“编辑”、“测试”、“文档”菜单

### ISSUE THREAD

**Issue by ArthurianCN** [eolinker/eoapi#91]
如下图对比
![image](https://user-images.githubusercontent.com/63100792/177482900-8c9ff01e-09bf-4e03-8dda-45d363887826.png)
![image](https://user-images.githubusercontent.com/63100792/177483005-bbac1092-bed6-4d0d-99c8-88778ee4e671.png)

操作系统：Windows 10 21H2 19044.1766
软件版本：1.2.5.0 pre

**Comment by scarqin** [comment]
@ArthurianCN 感谢反馈，我们在新版本跟进这个问题
