### ISSUE TITLE
最小化、关闭、最大化按钮没有反应

### ISSUE THREAD

**Issue by ArthurianCN** [eolinker/eoapi#92]
安装完成后，直接打开，三个按钮都没有反应，后台关闭后再次打开也一样
操作系统：Windows 10 21H2 19044.1766
软件版本：1.2.5.0 pre

**Comment by kungfuboy** [comment]
抱歉，我们的工作流程出现了一些失误，因此导致您自动升级到了 pre release 版本，我们已经撤回了这个版本。
