### ISSUE TITLE
Where is the code for the proxy module

### ISSUE THREAD

**Issue by CryptoThread** [eolinker/eoapi#95]
找不到proxy代理在哪边，有时候测试接口没反应

**Comment by scarqin** [comment]
@CryptoThread 麻烦提供更多的信息：
1. 你在哪里进行测试，demo 网站还是桌面端？
2. API 实际返回应该是什么？

**Comment by CryptoThread** [comment]
桌面端，然后也想知道代理的代码放在哪里了

**Comment by scarqin** [comment]
代码在这，已经打包进桌面端了
![](https://user-images.githubusercontent.com/15225835/178092582-b9d02e42-cda7-4cb3-a5e0-c52a2862c407.png)

**Comment by CryptoThread** [comment]
找过了，找不到
![image](https://user-images.githubusercontent.com/68012855/178092699-ad37e749-f78d-4674-8008-b1d0d619fc2b.png)

**Comment by scarqin** [comment]
请提供以下信息，暂不清楚你的具体诉求，沟通效率比较低。
1. API 实际返回应该是什么？
2. 请截图一下表现，我们可以排查
3. 找代码的意图是？需要自己开发排查吗？
